desc("Build files such as TypeScript and Sass");
task("build", function (params) {
  var cmd = "tsc @tscopt ./crawler/crawler.ts";
  console.log(cmd);
  jake.exec([cmd], {printStdOut : true, printStderr : true, breakOnError : false}, function() {
    cmd = "cd ./_build/pre/; ts-yield -o ../../_build/ ./crawler/* ./lib/*";
    console.log(cmd);
    jake.exec([cmd], {printStdOut : true, printStderr : true, breakOnError : false}, function() {
      console.log("Build complete");
      complete();
    });
  });
});
